language: node_js
node_js:
  - 6.7.0

cache:
  directories:
  - node_modules

before_install:
  - npm install codecov.io coveralls
  
install:
  - snyk protect
  - snyk test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - snyk monitor

script:
  - npm test -- --coverage

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=1BXJrX0DTLvcULsgbPMRfIS6hb1C50Wpm
